version: '3'

services:
  db:
    build: 
      dockerfile: ./docker/db/Dockerfile
      context: .
    image: 46163131231233/banco26
    container_name: banco26
    ports:
      - "3306:3306"
    networks: 
      - rede
  
  app:
    build: 
      dockerfile: ./docker/app/Dockerfile
      context: .
    image: 46163131231233/projeto26 
    container_name: projeto26
    ports: 
      - "3000:3000"
    networks: 
      - rede
    depends_on:
      - db
    links:
      - db
      
networks: 
  rede:
    driver: bridge