version: '3'

services:
  db:
    image: mariadb    
    ports:
      - "3306:3306"
    volumes:
      - /home/node/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root     
    networks: 
      - rede
  
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    image: 46163131231233/projeto26 
    container_name: projeto26
    ports: 
      - "3000:3000"
    networks: 
      - rede
      
networks: 
  rede:
    driver: bridge